[package]
name = "BasicCoin"
version = "0.0.0"

[addresses]
BasicCoin = "0xBC"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin.git", subdir="vm/stdlib", rev="1429e6e49d1a8e39c8515105080b3fbb877da372"}