[package]
name = "CoinSwap"
version = "0.0.0"

[addresses]
CoinSwap = "0xC5"
BasicCoin = "0xBC"
GoldCoin = "0x9C"
SilverCoin = "0x5C"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin.git", subdir="vm/stdlib", rev="3e895169a8f8dd883277050bb90645c52a370cee"}
BasicCoin = { local = "../basic-coin"}
